# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Generator-PerlData
version:      0.91
version_from: PerlData.pm
installdirs:  site
requires:
    perl:                          5.06
    XML::SAX::Base:                1.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
